### PR TITLE
Update problem.md

### PR DESCRIPTION
**Pull request by mgruesbeck**
Verify is looking for the number 45. However, the direction say to set the limit to 10.

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Not quite :) Please read through the instructions again - it says to add them all up.

**Comment by mgruesbeck** [comment]
Hi @SomeoneWeird,

Thanks for the note. It's very possible I am missing something. :) In any case, I am still scratching my head. Here are my thoughts on the problem/directions:

In that file define a variable named total and make it equal the number 0:
```var total = 0;```

Define a second variable named limit and make it equal the number 10:
```var limit = 0;```

Create a for loop with a variable i starting at 0 and increasing by 1 each time through the loop. The loop should run as long as i is less than limit. On each iteration of the loop, add the number i to the total variable. After the for loop, use console.log() to print the total variable to the terminal:
```
var total = 0;
var limit = 10; 

for (var i=0; i<limit; i++) {
    total += 1;
}

console.log(total);
```

Is the code above correct?

The validator fails it because it is looking for a total equal to 45. However, if we add by 1 on each loop and stop at 10 we never reach 45.

**Comment by SomeoneWeird** [comment]
Nearly! You need to add the value of `i` to `total` each time, instead of `1`.

**Comment by mgruesbeck** [comment]
Wow! I am a fool! :)

**Pull request closed without merging**
