### PR TITLE
Add Ukrainian translation.

### PR DESCRIPTION
**Pull request by denysdovhan**
HI!
I've translated this workshop on Ukrainian for our event by **NodeSchool Chernivtsi** chapter — 24 October, 2015.

Please, check my request and merge as soon as it possible.

**BTW:** @terry-s, @sudodoki or @komarnitskyi can check my translation.

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Can you squash all of these commits into a single one? 

After somebody has reviewed, I'll merge :)

**Comment by denysdovhan** [comment]
OK, no problem. But after checking these commits.

**Comment by terry-s** [comment]
I'll check it today, but later.

**Comment by denysdovhan** [comment]
Should I really squash all commits? Then I'll need to do `git push -f`, so that is not good. Or that's doesn't matter?

**Comment by SomeoneWeird** [comment]
Force pushing doesn't matter seeing as it only updates your branch. Indeed you shouldn't do it on an important branch like `master` - but in this case it doesn't matter.

**Comment by komarnitskyi** [comment]
I've checked, everything well

**Comment by SomeoneWeird** [comment]
Don't worry about squashing :)

**Comment by denysdovhan** [comment]
Ehm... okay, nice :)

**Pull request merged**
