### PR TITLE
Give a human error message when passed an invalid path.

### PR DESCRIPTION
**Pull request by samccone**
#### What

It is easy to forget that typing skills are highly variable across people not programming every day. When someone messes up the file name for one of the verify paths they are given a very scary message! Let's help people by providing a human message that is actionable without the help from someone who can understand the confusing error.

#### Before
screen shot 2016-02-24 at 9 05 50 pm

#### After
screen shot 2016-02-24 at 9 05 39 pm

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Very nice, are we polyfilling promises already?

**Comment by samccone** [comment]
What is the node support range we want here? I can ponyfill it for older node versions if we want. I figured since this is typically run by people brand new to node they are probally downloading node for the first time.. Thus this would be fine

**Comment by martinheidegger** [comment]
@samccone At the nodeschool i am running often the beginners are people that installed node 1 or 2 years ago and never touched it before. I still expect 0.12

**Comment by samccone** [comment]
Sgtm I will update to ensure we are golden on 0.10+

**Comment by martinheidegger** [comment]
Also: https://github.com/workshopper/workshopper-adventure/blob/master/i18n/en.json#L35 There is a **translated** field for a missing file.

**Comment by samccone** [comment]
hi @martinheidegger All updated to use the translated field

**Comment by samccone** [comment]
Hi @SomeoneWeird && @martinheidegger is there anything else I can do here?

I **really** appreciate your time thanks a million!

**Comment by SomeoneWeird** [comment]
Sorry, didn't see you update this! :tada:

**Comment by SomeoneWeird** [comment]
@sethvincent can you do a release? this would be really useful to get out (would be great if you could add myself and maybe martin as owners on npm too so we can publish if needed)

**Comment by sethvincent** [comment]
@SomeoneWeird published! and added you and @martinheidegger as npm owners. :tada:

**Comment by SomeoneWeird** [comment]
woop woop, thanks @samccone !

**Pull request merged**
