### PR TITLE
Add Italian translations

### PR DESCRIPTION
**Pull request by claudiopro**
Hi @sethvincent please consider accepting these translations to Italian. It seems workshopper itself is not translated to Italian, therefore some string resources are missing. I'll prepare translations for workshopper itself shortly.

### CODE REVIEW

**Comment by claudiopro** [comment]
@martinheidegger hi Martin, perchance do you also maintain this repo?

**Comment by a0viedo** [comment]
Hi @claudiopro, thanks for the contribution! I could also merge your pull request, but would love someone who speaks Italian to give a thumbs up first. Do you know anyone who could review it?

**Comment by claudiopro** [comment]
Hi @a0viedo, I can ask @lambrojos who's reviewing my translation of `learnyounode` also.

**Comment by claudiopro** [comment]
@a0viedo hi, what are the next steps on this PR ?

**Comment by a0viedo** [comment]
Awesome work @claudiopro and @lambrojos. Could you please squash the changes into one commit?

Next step after merging would be to do a npm release, but I'm not able to do that. Maybe @martinheidegger?

**Comment by claudiopro** [comment]
@a0viedo yup, let me do that

**Comment by sethvincent** [comment]
i can do an `npm publish` when this is ready.

(sidenote: i keep meaning to add a CONTRIBUTING.md file with open open source style guidelines and add npm collaborators. that should happen.)

**Comment by claudiopro** [comment]
@a0viedo @sethvincent gasp, I think I got them all. @lambrojos please have a look in case I missed something.

**Comment by lambrojos** [comment]
@a0viedo @sethvincent @claudiopro 
ok, everything looks fine from here :)

**Comment by a0viedo** [comment]
Done. @sethvincent all set for that `npm publish`. If I find some time these days will help with the CONTRIBUTING.md

**Pull request merged**
