### PR TITLE
Translation pt-br

### PR DESCRIPTION
**Pull request by AlanCezarAraujo**

### CODE REVIEW

**Comment by fmoliveira** [comment]
Hello guys,

Sorry for the late review.

I've submitted a pull request to @AlanCezarAraujo 's fork. There were just tiny typo issues, the translation is just great.

@AlanCezarAraujo , after accepting the PR, your original PR here in sethvincent's repo will be automatically updated.

**Comment by SomeoneWeird** [comment]
Awesome :tada:

**Comment by fmoliveira** [comment]
It looks like @AlanCezarAraujo has been inactive for some days.

@SomeoneWeird Perhaps we could merge his PR and later then I can submit a new PR fixing some few and tiny typos.

**Comment by fmoliveira** [comment]
It looks like @AlanCezarAraujo has been inactive for some days.

@SomeoneWeird Perhaps we could merge his PR and later then I can submit a new PR fixing some few and tiny typos. Alan's translation is nearly perfect, I've had to [adjust very few words](https://github.com/fmoliveira/javascripting/commit/50cc47fe09bac3206b30475c30854e4014c8f424).

**Comment by SomeoneWeird** [comment]
@fmoliveira sure thing

**Comment by fmoliveira** [comment]
@SomeoneWeird Good! I've just created [a new pull request](https://github.com/sethvincent/javascripting/pull/113) with the typos fixes. :)

**Comment by AlanCezarAraujo** [comment]
@fmoliveira Many thanks for your review!

**Comment by SomeoneWeird** [comment]
:+1:

**Comment by fmoliveira** [comment]
@AlanCezarAraujo I'm the one to thank you for the whole translation, it's just great! :smiley:

**Pull request merged**
